export const PROTECTED_ROUTES = {
  dashboard: "/",
  notification:"/notification",
  requests: "/requests",
  accepted_requests: "/accepted-requests",
  transport_control: "/transport-control",
  transport_control_driver: "/transport-control/driver",
  transport_control_trucks: "/transport-control/trucks",
  transport_control_issue_report: "/transport-control/issue-report",
  trucks: "/trucks",
  trips: "/trips",
  invoices: "/invoices",
  quality: "/quality",
  register: "/register",
  settings: "/settings",
  support: "/settings/support",
  profile_settings: "/settings/profile",
  notifications_settings: "/settings/notifications",
  recipients_settings: "/settings/recipients",
  transactions: "/transactions",
  transaction_history: "/transaction-history",
};
